### PR TITLE
Integrate milepost

### LINKED ISSUE #4: Route Milepost geometry
Biowest already has the gp service that accepts these inputs and returns the segment.

Their UI has a drop-down with all of the routes pre-populated. This might be helpful to prevent input errors.

If we want to use the stuff from roadkill it's here...
widget: https://subversion.dts.utah.gov/agrc-roadkillreporterdesktop/trunk/content/roadkill/RouteMilepostFilter.js
gp service script: https://subversion.dts.utah.gov/agrc-roadkillreporterdesktop/scripts/RouteMilepostsSegment.py

### PR DESCRIPTION
**Pull request by steveoh**
fixes #4

### CODE REVIEW

**Comment by stdavis** [comment]
I wonder if `routes.js` should come from a database instead of hard-coded. Just worried about future headaches trying to keep it updated.

**Comment by steveoh** [comment]
bert says it takes an act of congress to create a new highway. i think we
can be relaxed on it.

**Comment by stdavis** [comment]
Even state routes? Or are they not involved in this app.

**Comment by steveoh** [comment]
you'd have to ask @bgranberg but I think so.

**Comment by BGranberg** [comment]
act of state legislature

On Thu, Oct 24, 2013 at 8:09 AM, steve notifications@github.com wrote:

> bert says it takes an act of congress to create a new highway. i think we
> can be relaxed on it.
> 
> On Thu, Oct 24, 2013 at 6:57 AM, Scott Davis notifications@github.comwrote:
> 
> > I wonder if routes.js should come from a database instead of hard-coded.
> > Just worried about future headaches trying to keep it updated.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/agrc/PEL/pull/25#issuecomment-26989578>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/agrc/PEL/pull/25#issuecomment-26995130
> .

## 

Bert Granberg, Director
Utah Automated Geographic Reference Center (AGRC)
1 State Office Bldg, Rm 5130
Salt Lake City, UT 84114
bgranberg@utah.gov
801 538-3163 (o)
801 558 3563 (m)

**Pull request merged**
